project:
  type: website
  output-dir: _site

website:
  announcement:
    content: "This website is a work in progress. Please check back for updates."
    icon: info-circle
    position: below-navbar
    type: primary
  open-graph: true
  title: "Agentic AI: Workgroup"
  site-url: https://wfu-agentic-ai.github.io/workgroup/
  repo-url: https://github.com/wfu-agentic-ai/workgroup
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Sessions
        href: sessions/index.qmd
      - text: Tutorials
        href: tutorials/index.qmd
      - text: Resources
        href: resources/index.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/wfu-agentic-ai/workgroup

format:
  html:
    theme:
      light: [simplex, assets/theme-light.scss]
      dark: [simplex, assets/theme-dark.scss]
    css: styles.css
    toc: true
    code-copy: true
    link-external-newwindow: true

execute:
  freeze: true
